### ISSUE TITLE
Errors on running registration

### ISSUE THREAD

**Issue by qshzh** [nicolas-chaulet/torch-points3d#476]
Thanks for share this amazing work. I want to try torch-points3d on registration tasks. However, I encounter some problems.

1. I encounter the transform errors in the ETHDataset and Kaist. [Log of ETHDataset](https://wandb.ai/qinsheng/default/runs/2mm2pvdo/logs?workspace=user-qinsheng) 
```
  File "/data/torch-points3d/torch_points3d/datasets/registration/basetest.py", line 448, in __getitem__
    return self.get_fragment(idx)
  File "/data/torch-points3d/torch_points3d/datasets/registration/base_siamese_dataset.py", line 142, in get_fragment
    data_source, data_target, new_pair = self.get_raw_pair(idx)
  File "/data/torch-points3d/torch_points3d/datasets/registration/basetest.py", line 444, in get_raw_pair
    data_source_o, data_target_o)
  File "/data/torch-points3d/torch_points3d/datasets/registration/base_siamese_dataset.py", line 122, in unsupervised_preprocess
    data_source = t1(data_source_o.clone())
  File "/data/torch-points3d/torch_points3d/core/data_transform/transforms.py", line 892, in __call__
    data = apply_mask(data, mask)
  File "/data/torch-points3d/torch_points3d/core/data_transform/transforms.py", line 715, in apply_mask
    if(size_pos == len(data[k]) and k not in skip_keys):
TypeError: object of type 'float' has no len()
```

2. Registration performance shown in the [paper](https://arxiv.org/pdf/2010.04642.pdf) looks good. When I run on 3DMatch dataset, there are also some weired error. Such as array not in same shape in the [line](https://github.com/nicolas-chaulet/torch-points3d/blob/e8f99ca60b22ea591e7219cc1989a68e31d955ac/torch_points3d/datasets/registration/pair.py#L218) and RuntimeError: CUDNN_STATUS_MAPPING_ERROR in `MLP2D`. I guess I run with wrong command or maybe miss something important.
It will be great if there are more details on how to reproduce results. 

3. By the way, the auto-download and process in registration datasets have a small bug. The source code of [TORCH_GEOMETRIC Dataset](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/data/dataset.html#Dataset)
```python
        if 'download' in self.__class__.__dict__.keys():
            self._download()

        if 'process' in self.__class__.__dict__.keys():
            self._process()
```
If we design `Fragment3DMatch` inherited from `Base3DMatch`, where the download and process methods are defined in `Base3DMatch`, `download` and `process` are not in `self.__class__.__dict__.keys()`. Maybe we should consider explicitly call download and process during initialization of Fragment3DMatch.

**Comment by humanpose1** [comment]
Hi,

First thank you very much for your report ! It allows to see some errors I've made.

1) the error is because you type this command.
`train.py task=registration model_type=pointnet2 model_name=minipointnet2 dataset=testeth training.batch_size=2 wandb.log=True training.num_workers=0 training=default_reg` 
Actually to train feature matching algorithms, there are two ways:
- patch based methods (For example 3DMatch, ppfNet, 3DSmoothnet or the recent DIP)
- fragment based methods (using a unet structure) (FCGF, D3Feat...)
Patch based methods are only implemented for 3DMatch and haven't been tested correctly...
So you tried a patch based model on fragment dataset....
you can try 
`train.py task=registration model_type=pointnet2 model_name=pointnet2_charlesmsg dataset=testeth training.batch_size=2 wandb.log=True training.num_workers=0 training=default_reg`

I will better organize the conf files :)  

2) Here is the command I've typed to have the results:
for training: 
`train.py task=registration model_type=minkowski model_name=MinkUNet_Fragment dataset=fragment3dmatch_sparse training=sparse_fragment_reg training.epochs=200 wandb.name=MinkUNet_Fragment`
For testing
`
python scripts/test_registration_scripts/evaluate.py task=registration model_type=minkowski model_name=MinkUNet_Fragment dataset=fragment3dmatch_sparse  training.checkpoint_dir="your weights "  data.sym=True
`
You can download pretrained weights here https://cloud.mines-paristech.fr/index.php/s/9MBF45iYwQ4ASZd.
I will update the README for more information.

3) You're absolutely right.
I will try to fix it quickly.

Don't hesitate if you have other remarks ! :)

**Comment by qshzh** [comment]
Thanks for your timely and helpful response, I am still running some demos.
For the first question, I still encounter the same issue with your command, see [the log](https://wandb.ai/qinsheng/registration/runs/26a869ek/logs?workspace=user-qinsheng). I may not sure the reasons, but it seems the transformers are suspicious.

**Comment by humanpose1** [comment]
Yes You're right!
It's indeed because of the transformation(the transformation for the dataset testeth is not adapted).  Because Pointnet++ need batch of point cloud of the same size (Need a dense format) you need to add the following transform:
`- transform: FixedPoints
      lparams: [4096]`

Try rather this:
`train.py task=registration model_type=pointnet2 model_name=pointnet2_charlesmsg dataset=fragment3dmatch_dense training.batch_size=2 wandb.log=True training.num_workers=0 training=default_reg`

**Comment by qshzh** [comment]
I guess the code in the pair.py has a small bug when key like `grid_size`
```python
        for key in batch.keys:
            item = batch[key][0]
            if (
                torch.is_tensor(item)
                or isinstance(item, int)
                or isinstance(item, float)
            ):
                if key != "pair_ind":
                    batch[key] = torch.stack(batch[key])
```
Maybe 
```python
            if torch.is_tensor(item):
                if key != "pair_ind":
                    batch[key] = torch.stack(batch[key])
            elif (isinstance(item, int)
                  or isinstance(item, float)
                  ):
                batch[key] = torch.tensor(batch[key]).reshape(-1, 1)
```
Beside, the dense format approach has the another issue, [log](https://wandb.ai/qinsheng/registration/runs/2bhsr65u/logs?workspace=user-qinsheng):
```
Exception has occurred: RuntimeError
cuDNN error: CUDNN_STATUS_MAPPING_ERROR
  File "/data/torch-points3d/torch_points3d/modules/pointnet2/dense.py", line 72, in conv
    new_features = self.mlps[scale_idx](new_features)  # (B, mlp[-1], npoint, nsample)
  File "/data/torch-points3d/torch_points3d/core/base_conv/dense.py", line 81, in forward
    ms_x.append(self.conv(x, pos, new_pos, radius_idx, scale_idx))
  File "/data/torch-points3d/torch_points3d/models/base_architectures/unet.py", line 292, in forward
    data_out = self.down(data, **kwargs)
  File "/data/torch-points3d/torch_points3d/models/base_architectures/unet.py", line 293, in forward
    data_out2 = self.submodule(data_out, **kwargs)
  File "/data/torch-points3d/torch_points3d/models/registration/pointnet2.py", line 169, in apply_nn
    last_feature = self.model(input).x
  File "/data/torch-points3d/torch_points3d/models/registration/base.py", line 121, in forward
    self.output = self.apply_nn(self.input)
  File "/data/torch-points3d/torch_points3d/models/base_model.py", line 215, in optimize_parameters
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results
  File "/data/torch-points3d/torch_points3d/trainer.py", line 194, in _train_epoch
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "/data/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/data/torch-points3d/train.py", line 13, in main
    trainer.train()
  File "/data/torch-points3d/train.py", line 21, in <module>
    main()
```
Can you run the command successfully on your machine?
```
train.py task=registration model_type=pointnet2 model_name=pointnet2_charlesmsg dataset=fragment3dmatch_dense training.batch_size=2 wandb.log=True training.num_workers=0 training=default_reg
```
 Dense MLPs do not raise issues when I run other tasks, such as segmentation. I guess it is not because I run my code inside docker containers.

**Comment by humanpose1** [comment]
I'll change the code in `pair.py`. 
About the `CUDNN_STATUS_MAPPING_ERROR` I find it weird that it works on segmentation but not on registration.
In my computer, I can run the command without problem. Is it a problem of driver's version ?
what do you think @nicolas-chaulet   ?

**Comment by qshzh** [comment]
@humanpose1  can you share your driver's version and dependency version.

Here are the some information  about my docker environment. I use the almost same setting as in [Dockerfile.gpu](https://github.com/nicolas-chaulet/torch-points3d/blob/master/docker/Dockerfile.gpu) except using `python3.7` and base on `nvidia/cuda:10.1-devel-ubuntu18.04`. I can not find `nvcc` in `nvidia/cuda:10.2-devel-ubuntu18.04` and have some error raised. 
```shell
torch: 1.6.0+cu101
nvcc: V10.1.243
python: 3.7
```

**Comment by qshzh** [comment]
But it is strange if you can run with the unchanged `pair.py`. Didn't you encounter the same errors in `torch.stack(batch[key])`?

**Comment by nicolas-chaulet** [comment]
It could be cuda 10.1, we have never really used that version.

**Comment by humanpose1** [comment]
I tried with:
nvcc V10.1.168
torch 1.5.1
Python 3.7.5
But I use cuda 10.2
But I don't use Docker.
And I don't have problems with pair.py. 
When I execute the following command, `train.py task=registration model_type=pointnet2 model_name=pointnet2_charlesmsg dataset=fragment3dmatch_dense training.batch_size=2 wandb.log=True training.num_workers=0 training=default_reg` I don't have any problem and the loss is decreasing.
Just, can you please write a simple code where `pair.py` is failing  ? (like this [tests](https://github.com/nicolas-chaulet/torch-points3d/blob/master/test/test_msdatapair.py)  for example).

**Comment by qshzh** [comment]
@humanpose1 @nicolas-chaulet Thanks for your response and help. It turns out the issue is caused by cuda. I try the command with cuda 10.2. The issue raised in `pair.py` and `CUDNN_STATUS_MAPPING_ERROR` disappear.

**Comment by nicolas-chaulet** [comment]
Perfect, closing for now.
