### ISSUE TITLE
CUDA version mismatch issue in the Colab example notebooks

### ISSUE THREAD

**Issue by Aditya1001001** [nicolas-chaulet/torch-points3d#563]
I was trying to run the ObjectClassificationRSConv [notebook](https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/ObjectClassificationRSConv.ipynb)

`from torch_points3d.datasets.classification.modelnet import SampledModelNet` throws the error: 

`RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 11.0. Please reinstall the torch_sparse that matches your PyTorch install.`

I have tried uninstalling `torch-scatter` and `torch-sparse`, reinstalling them with the correct CUDA version.

```
!pip uninstall torch-scatter torch-sparse
!pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
```
But the problem still persists.  How can I fix this?

**Comment by CCInc** [comment]
@Aditya1001001 usually this can be resolved by passing --no-cache-dir to pip install. Pip likes to use the already downloaded wheels. Please try this:

```
!pip uninstall torch-scatter torch-sparse
!pip install --no-cache-dir torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
```

**Comment by Fautos** [comment]
@CCInc thanks a lot, your solution totaly works for me.
Only wanted to noticed that you also need to do the same with the torch-cluster. The final code looks like:

`!pip uninstall torch-scatter torch-sparse torch-cluster -y`
`!pip install --no-cache-dir torch-scatter torch-sparse torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html`

Again thanks a lot, i´ve beeing struggling with this problem for a long time.

**Comment by nicolas-chaulet** [comment]
Great to hear! Closing the issue as resolved
